version: '2'
services:
  hcx_exporter:
    # Using the latest tag, but you can use vers(v0.9.5 for example
    image: hcx_exporter:dev
    ports:
        - "9000:9000"
    environment:
        VMWARE_HCX_IP: "vcenter-host"
        VMWARE_HCX_ID: ""
        VMWARE_HCX_PW: ""
        SSL_VERIFY: "True"
#        COLLECT_VMS: "False"
#        COLLECT_VMGUESTS: "False"
    restart: always
    #FOR DEBUG UNCOMMENT NEXT LINE
    #command: ["-l","DEBUG"]
